### ISSUE TITLE
error running example

### ISSUE THREAD

**Issue by enriluis** [rklf/yopmail#5]
`python3 yopmail/example.py
Traceback (most recent call last):
  File "yopmail/example.py", line 3, in <module>
    from yopmail import Yopmail
  File "/home/lmb/yopmail/yopmail/__init__.py", line 1, in <module>
    from .yopmail import Yopmail
  File "/home/lmb/yopmail/yopmail/yopmail.py", line 29, in <module>
    class Yopmail:
  File "/home/lmb/yopmail/yopmail/yopmail.py", line 45, in Yopmail
    def request(self, url: str, params=None, proxies=None, context: str = None) -> requests.models.Response|None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
`

**Comment by rklf** [comment]
Use Python >= 3.10

**Comment by enriluis** [comment]
thanks! This script skip or solve yopmail capcha?

**Comment by rklf** [comment]
Didn't got time so not currently, but feel free to add a PR to do this using services such as 2captcha or anti-Captcha. 

Otherwise you can still use proxies which are fully-implemented (make sure proxies are not blacklisted or captcha-locked though)
